### ISSUE TITLE
Error tapping brew formula

### ISSUE THREAD

**Issue by neeraj-htp** [nats-io/homebrew-nats-tools#9]
Error Running command `brew tap nats-io/nats-tools` on mac with intel chip set. 
``` log
==> Tapping nats-io/nats-tools
Cloning into '/usr/local/Homebrew/Library/Taps/nats-io/homebrew-nats-tools'...
remote: Enumerating objects: 214, done.
remote: Counting objects: 100% (214/214), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 214 (delta 47), reused 24 (delta 5), pack-reused 0
Receiving objects: 100% (214/214), 39.06 KiB | 1.05 MiB/s, done.
Resolving deltas: 100% (47/47), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/nats-io/homebrew-nats-tools/Formula/nsc.rb
formulae require at least a URL
Error: Cannot tap nats-io/nats-tools: invalid syntax in tap!
```

Because [this](https://github.com/nats-io/homebrew-nats-tools/commit/c3f220d2ff7213d75190c43005409b893b12a4ee) commit removed the intel CPU check.

**Comment by neeraj-htp** [comment]
@goreleaserbot

**Comment by philpennock** [comment]
This is from the goreleaser brews integration.  I am looking now.

**Comment by philpennock** [comment]
Upgrading goreleaser-pro from 1.8.1 to 1.8.3 fixes this issue.  I will fix for the future and see about fixing the current brew spec.

**Comment by philpennock** [comment]
https://github.com/nats-io/nsc/pull/489 should have fixed this going forward.

**Comment by philpennock** [comment]
The current 2.7.1 formula has been fixed too.

Thank you for the report!  Much appreciated.
